create database STORE;


CREATE TABLE PRODUCT ( PRDID INT PRIMARY KEY, PNAME VARCHAR(20), PRICE INT, QUANTITY INT);


DELIMITER $$

CREATE PROCEDURE Insertproduct(
    IN PRODUCT_PRDID INT,
    IN PRODUCT_PNAME VARCHAR(100),
    IN PRODUCT_PRICE DECIMAL(10,2),
    IN PRODUCT_QUANTITY INT
)
BEGIN
    
    IF PRODUCT_PRICE > 0 AND PRODUCT_QUANTITY >= 0 THEN
        INSERT INTO Product (PRDID, PNAME, PRICE, QUANTITY)
        VALUES (PRODUCT_PRDID, PRODUCT_PNAME, PRODUCT_PRICE, PRODUCT_QUANTITY);
    END IF;
END $$

DELIMITER ;

SELECT * FROM PRODUCT;


CALL Insertproduct(102, 'Shampoo', 5, 10);
CALL Insertproduct(103, 'Oil', 50, -2);