CREATE DATABASE SALES;
USE SALES;

CREATE TABLE PRODUCT(
	PDTID INT PRIMARY KEY,
    PNAME VARCHAR(20),
    PRICE DECIMAL(10,2),
    QTYSTOCK INT
    );
    
    CREATE TABLE SALE(
		SALEID INT PRIMARY KEY,
        DELIVERYADDRESS VARCHAR(200)
        );
        
	CREATE TABLE SALEITEM(
		SALEID INT,
        PDTID INT, 
        QTY INT,
        PRIMARY KEY (SALEID,PDTID),
        foreign key (SALEID) references SALE(SALEID),
        foreign key (PDTID) REFERENCES PRODUCT(PDTID)
        );
        
        
         DELIMITER $
	CREATE TRIGGER qty_update
    AFTER INSERT
    ON SALEITEM FOR EACH ROW
   
    BEGIN
    UPDATE PRODUCT
    SET QTYSTOCK=QTYSTOCK-NEW.QTY
    WHERE PDTID=NEW.PDTID AND QTYSTOCK>=NEW.QTY;
    END $
    DELIMITER ;
    
  INSERT INTO PRODUCT (PDTID, PNAME, PRICE, QTYSTOCK) VALUES
(101, 'Laptop', 50000.00, 10),
(102, 'Mouse', 500.00, 50),
(103, 'Keyboard', 1500.00, 30),
(104, 'Monitor', 12000.00, 15);

INSERT INTO SALE (SALEID, DELIVERYADDRESS) VALUES
(1, 'Kochi, Kerala'),
(2, 'Kannur, Kerala'),
(3, 'Calicut, Kerala');


select * FROM PRODUCT;

INSERT INTO SALEITEM (SALEID, PDTID, QTY) VALUES
(1, 101, 2),
(1, 102, 5),
(2, 103, 3),
(3, 104, 1);